export default [
    "BASIC_SEARCH", "ADVANCED_SEARCH", "BROWSE_MAIN_SITE", "RESTRICTED_INTERACTION",
    "PROFILE_CREATION", "DOCUMENT_UPLOAD", "JOB_SEARCH", "JOB_APPLICATION_LIMIT",
    "MESSAGE_RESTRICTIONS", "INDIRECT_CONTACT", "JOB_NOTIFICATIONS", "LIMITED_COMMUNICATION",
    "PROFILE_VISIBILITY", "MANDATORY_DOCUMENTS", "DOCUMENT_CHECKS", "TRAINING_COURSE_SEARCH",
    "AVAILABILITY_CALENDAR", "PROFILE_UPDATES", "JOB_LISTINGS_APPLICATION", "PAY_PER_CLICK_ADS",
    "DOCUMENT_ACCESS_REQUESTS", "ACCESS_REQUEST_NOTIFICATIONS", "INSURANCE_BADGE",
    "UNLIMITED_JOB_APPLICATIONS", "DIRECT_MESSAGING", "ADVANCED_SEARCH_ACCESS",
    "PRIORITY_PROFILE_LISTING", "AI_MATCHING", "VERIFICATION_BADGE", "FULL_FEATURE_ACCESS",
    "AI_OPTIMIZATION", "PERSONALIZED_SUPPORT", "DOCUMENT_VERIFICATION_FAST_TRACK",
    "TRAINING_COURSE_ACCESS", "FULL_MESSAGING", "DOCUMENT_ACCESS", "JOB_AD_POSTING",
    "REVENUE_GENERATION", "COURSE_AD_PLACEMENT", "AI_FEATURES"
]